apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: rook-ceph
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:focal
    command: ["tail","-f", "/dev/null"]
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
  restartPolicy: Always