---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps.yaml
  - cert-manager.yaml
  - crypto.yaml
  - firefly.yaml
  - hajimari.yaml
  - media.yaml
  - metallb-system.yaml
  - networking.yaml
  - monitoring.yaml
  - openebs-system.yaml
  - paperless.yaml
  - postgres.yaml
