---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.8.5
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  dependsOn:
    - name: rook-ceph
  values:
    monitoring:
      enabled: false
    ingress:
      dashboard:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        host:
          name: "rook.${SECRET_DOMAIN}"
          path: "/"
        tls:
          - hosts:
              - "rook.${SECRET_DOMAIN}"
    cephClusterSpec:
      mon:
        count: 1
      dashboard:
        enabled: true
        ssl: false
        port: 8555
      storage:
        useAllNodes: true
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "talos"
            devices:
              - name: "/dev/sda"
    cephObjectStores: []